%% Template Matlab script to create an BIDS compatible _bold.json file
% https://github.com/bids-standard/bids-starter-kit/blob/master/matlabCode/func/createBIDS_bold_json_full.m
% https://github.com/gllmflndn/JSONio

%%
function write_bold_josn(output_dir,sub_label,task_label,run_label)

% output_dir = ['..' filesep '..'];
% sub_label = '01';
% task_label = 'FullExample';
% run_label = '01';

% 
bold_json_name = fullfile(output_dir,...
    ['sub-' sprintf('%02d',str2double(sub_label)) ...
    '_task-' task_label ...
    '_run-' sprintf('%02d',run_label) '_bold.json']);



%% template

    bold_json.Modality = 'MR';
    bold_json.MagneticFieldStrength = 3;
    bold_json.ImagingFrequency = 127.7659;
    bold_json.Manufacturer = 'GE MEDICAL SYSTEMS';
    bold_json.ManufacturersModelName = 'DISCOVERY MR750';
    bold_json.InstitutionName = 'Duke Univ Hosp MR5';
    bold_json.InstitutionalDepartmentName = 'Center for Cognitive Neuroscience';
    bold_json.InstitutionAddress = 'LSRC';
    bold_json.DeviceSerialNumber = '0000000919684MR5';
    bold_json.StationName = 'bia5';
    bold_json.BodyPartExamined = 'BRAIN';
    bold_json.PatientPosition = 'HFS';
    bold_json.ProcedureStepDescription = 'decodCC.01';
    bold_json.SoftwareVersions = '24_LX_MR Software release:DV24.0_R01_1344.a';
    bold_json.MRAcquisitionType = '2D';
    bold_json.SeriesDescription = sprintf('task-%s_run%02d',task_label,run_label);
    bold_json.ProtocolName = sprintf('task-%s_run%02d',task_label,run_label);
    bold_json.ScanningSequence = [
        'EP',...
        'GR'
    ];
    bold_json.SequenceVariant = 'SS';
    bold_json.ScanOptions = [
        'EPI_GEMS',...
        'ACC_GEMS'
    ];
    bold_json.ImageType = [
        'ORIGINAL',...
        'PRIMARY',...
        'EPI',...
        'NONE'
    ];
    bold_json.SeriesNumber = run_label;
    bold_json.SliceThickness = 3;
    bold_json.SpacingBetweenSlices = 3;
    bold_json.EchoTime = 0.03;
    bold_json.RepetitionTime = 2;
    bold_json.FlipAngle = 80;
    bold_json.ReceiveCoilName = '8HRBRAIN';
    bold_json.EchoTrainLength = 1;
    bold_json.AcquisitionMatrixPE = 64;
    bold_json.PixelBandwidth = 7812.5;
    bold_json.PhaseEncodingDirection = 'j-';
    bold_json.SliceTiming = [
        0.0500,...
        0.1500,...
        0.2500,...
        0.3500,...
        0.4500,...
        0.5500,...
        0.6500,...
        0.7500,...
        0.8500,...
        0.9500,...
        1.0500,...
        1.1500,...
        1.2500,...
        1.3500,...
        1.4500,...
        1.5500,...
        1.6500,...
        1.7500,...
        1.8500,...
        1.9500,...
        0.1000,...
        0.2000,...
        0.3000,...
        0.4000,...
        0.5000,...
        0.6000,...
        0.7000,...
        0.8000,...
        0.9000,...
        1.0000,...
        1.1000,...
        1.2000,...
        1.3000,...
        1.4000,...
        1.5000,...
        1.6000,...
        1.7000,...
        1.8000,...
        1.9000,...
        2.0000
    ];
    bold_json.InPlanePhaseEncodingDirectionDICOM = 'COL';
    bold_json.TaskName = 'decodCC.01';


%% Write
% this just makes the json file look prettier when opened in a text editor
json_options.indent = '    ';

jsonSaveDir = fileparts(bold_json_name);
if ~isdir(jsonSaveDir)
    fprintf('Warning: directory to save json file does not exist, first create: %s \n',jsonSaveDir)
end

try
    jsonwrite(bold_json_name,bold_json,json_options)
catch
    warning( '%s\n%s\n%s\n%s',...
        'Writing the JSON file seems to have failed.', ...
        'Make sure that the following library is in the matlab/octave path:', ...
        'https://github.com/gllmflndn/JSONio')
end

end